import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

import {Providers} from "@/app/providers";
import MainNavbar from '@/components/Navbar/MainNavbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="relative bg-cover bg-center h-screen flex items-center justify-center" style={{ backgroundImage: "url('/app/sign/zipircomsign.png')" }}>
        <Providers>
              {children}
         </Providers>
        </div>
      </body>
    </html>
  )
}
